name: GitHub Pages

on: 
  workflow_dispatch:
  push:
    branches: [ main ]  # Add automatic trigger on push to main

# Add proper permissions
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Checkout notion-md tool
        uses: actions/checkout@v4  # Updated to v4
        with:
          repository: Malsius/notion-md
          path: notion-md
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install Python dependencies
        run: |
          cd notion-md
          pip install -r requirements.txt || echo "No requirements.txt found"
      
      - name: Make script executable
        run: chmod +x notion-md/script.py
      
      - name: Fetch Notion pages
        run: python notion-md/script.py --static static/images --content content/posts --url /notion-ghpages/images --db "${{ secrets.NOTION_DB_ID }}" --key "${{ secrets.NOTION_API_KEY }}" --hugo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install/Update Hugo modules (if using modules)
        run: hugo mod get -u || echo "No Hugo modules to update"

      - name: Build Hugo site
        run: hugo --minify
      
      - name: Create CNAME file
        run: echo "www.renewszero.com" > CNAME

      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
